apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template: 
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: grich966/posts
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: posts-cluster-srv
spec:
  selector:
    app: posts
  type: ClusterIP
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000

# Creates a pod for the post service & exposes port 4005 via a ClusterIP service